#include "CommonParticleComputeShader.compute"
#include "PerlinNoise.hlsl"

SimOutput GetDistancePerlinNoiseJob(float3 pos)
{
    SimOutput simOutput;

    float x = pos.x;
    float y = pos.y;
    float z = pos.z;

    // TODO: Actual perlin noise
    // float perlin = rand_float(float2(x * 0.2f, z * 0.2f));
    float perlin = snoise(float2(x * 0.1f, z * 0.1f));

    simOutput.dist = y - perlin * 6.0f;
    simOutput.normal = float3(0.0, 1.0, 0.0);

    return simOutput;
}
