#include "CommonParticleComputeShader.compute"

SimOutput GetDistanceSphereFieldJob(float3 pos)
{
    SimOutput simOutput;

    float spacing = 5.0f + sin(gTime * 5.0f) * 2.0f;
    float spacingVector = spacing * 0.5f;
    pos += spacingVector;
    pos -= floor(pos / spacing) * spacing;
    pos -= spacingVector;

    simOutput.dist = Sphere(pos, 5.0f);
    simOutput.normal = pos;

    return simOutput;
}
